#!/bin/bash

##Pod-1:
podman pod create --name prometheus --publish 9090:9090 --publish 3000:3000

##Prometheus
podman run -itd --pod prometheus --name prom -v /home/yogendra/guacamole/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml docker.io/prom/prometheus

##Grafana
podman run -itd --pod prometheus --name grafana docker.io/grafana/grafana


##Pod-2:
podman pod create --name guacamole --publish 9080:8080 --publish 4822:4822 --publish 9256:9256 --publish 9187:9187 --publish 5432:5432 --publish 5556:5556 --publish 9999:9999

##guacamole-postgres
podman run -dt --pod guacamole --name guacamole-postgres -e POSTGRES_DB=guacamole_db -e POSTGRES_USER=guacamole_user -e POSTGRES_PASSWORD=redhat -e PGDATA=/var/lib/postgresql/data/pgdata -v /home/yogendra/guacamole/guacamole-postgres/postgres:/var/lib/postgresql/data  docker.io/postgres

##guacamole-guacd
podman run -dt --pod guacamole --name guacamole-guacd  docker.io/guacamole/guacd


##guacamole-app
podman run -idt --pod guacamole --name guacamole-app  -v /home/yogendra/guacamole/guacamole-app/tomcat.yaml:/usr/local/tomcat/bin/tomcat.yml -v /home/yogendra/guacamole/guacamole-app/jmx_prometheus_javaagent-0.16.1.jar:/usr/local/tomcat/bin/jmx_prometheus_javaagent-0.16.1.jar  -v /home/yogendra/guacamole/guacamole-app/setenv.sh:/usr/local/tomcat/bin/setenv.sh -e POSTGRES_HOSTNAME=localhost -e POSTGRES_DATABASE=guacamole_db -e POSTGRES_USER=guacamole_user -e POSTGRES_PASSWORD=redhat -e GUACD_HOSTNAME=localhost  docker.io/guacamole/guacamole

##pgsql-exporter
podman  run -itd --pod guacamole --name pgsql-exporter -e DATA_SOURCE_NAME="postgresql://guacamole_user:redhat@127.0.0.1:5432/guacamole_db?sslmode=disable" quay.io/prometheuscommunity/postgres-exporter
podman  run -itd --pod guacamole --name process-exporter --privileged -v /proc:/host/proc docker.io/ncabatoff/process-exporter

